import { createFileRoute } from "@tanstack/react-router";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import { useMutation } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  Sparkles,
  TrendingUp,
  AlertTriangle,
  Trophy,
  Compass,
  Send,
  Loader2,
  RefreshCw,
} from "lucide-react";
import { useFinance } from "@/lib/store";
import { buildSnapshot } from "@/lib/snapshot";
import { computeStats } from "@/lib/finance";
import { formatCurrency } from "@/lib/currency";
import { PageHeader, Card } from "@/components/app/page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import type { AIReport, AIInsight } from "@/lib/types";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_app/ai")({
  head: () => ({
    meta: [
      { title: "AI Analytics — Wealth" },
      { name: "description", content: "Gemini-powered AI financial intelligence." },
    ],
  }),
  component: AIPage,
});

function AIPage() {
  const profile = useFinance((s) => s.profile);
  const txns = useFinance((s) => s.transactions);
  const budgets = useFinance((s) => s.budgets);
  const goals = useFinance((s) => s.goals);
  const aiReport = useFinance((s) => s.aiReport);
  const setAIReport = useFinance((s) => s.setAIReport);

  const snapshot = useMemo(
    () => buildSnapshot(txns, budgets, goals, profile),
    [txns, budgets, goals, profile],
  );
  const stats = useMemo(() => computeStats(txns), [txns]);
  const fmt = (v: number) => formatCurrency(v, profile.currency);

  const generate = useMutation({
    mutationFn: async () => {
      const res = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ snapshot }),
      });
      if (!res.ok) {
        const msg =
          res.status === 429
            ? "Rate limited. Please wait a moment."
            : res.status === 402
              ? "AI credits exhausted."
              : "AI request failed.";
        throw new Error(msg);
      }
      return (await res.json()) as AIReport;
    },
    onSuccess: (r) => {
      setAIReport(r);
      toast.success("Insights generated");
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Something went wrong"),
  });

  // Auto-generate on first visit if no report
  useEffect(() => {
    if (!aiReport && txns.length > 0 && !generate.isPending) {
      generate.mutate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="min-h-screen">
      <PageHeader
        eyebrow="AI Analytics · Powered by Gemini"
        title="Your AI financial analyst"
        description="Real insights from your real data — generated by Gemini 3 Flash."
        actions={
          <Button onClick={() => generate.mutate()} disabled={generate.isPending}>
            {generate.isPending ? (
              <>
                <Loader2 className="mr-1 size-4 animate-spin" /> Generating
              </>
            ) : (
              <>
                <RefreshCw className="mr-1 size-4" /> Refresh report
              </>
            )}
          </Button>
        }
      />

      <div className="space-y-6 p-6 md:p-10">
        {/* AI Chat — top, iMessage style, constrained width */}
        <ChatPanel snapshot={snapshot} />

        {/* Hero report */}
        {generate.isPending && !aiReport ? (
          <ReportSkeleton />
        ) : aiReport ? (
          <ReportView report={aiReport} fmt={fmt} />
        ) : (
          <Card>
            <p className="text-sm text-muted-foreground">
              Click "Refresh report" above to generate your first AI analysis.
            </p>
          </Card>
        )}

        {/* Forecast block */}
        {aiReport && (
          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            <Card>
              <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                Projected end-of-month balance
              </p>
              <p className="mt-2 font-display text-2xl font-medium tracking-tight">
                {fmt(aiReport.forecast.endOfMonthBalance)}
              </p>
            </Card>
            <Card>
              <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                Projected monthly savings
              </p>
              <p
                className={cn(
                  "mt-2 font-display text-2xl font-medium tracking-tight",
                  aiReport.forecast.projectedSavings >= 0 ? "text-emerald-400" : "text-rose-400",
                )}
              >
                {fmt(aiReport.forecast.projectedSavings)}
              </p>
            </Card>
            <Card>
              <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                Current monthly net
              </p>
              <p className="mt-2 font-display text-2xl font-medium tracking-tight">
                {fmt(stats.monthlyIncome - stats.monthlyExpenses)}
              </p>
              <p className="mt-2 text-xs text-muted-foreground">{aiReport.forecast.note}</p>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}

function ReportSkeleton() {
  return (
    <div className="space-y-4">
      <Card>
        <div className="space-y-3">
          <div className="skeleton h-3 w-32" />
          <div className="skeleton h-8 w-2/3" />
          <div className="skeleton h-4 w-full" />
          <div className="skeleton h-4 w-4/5" />
        </div>
      </Card>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {[0, 1, 2, 3].map((i) => (
          <Card key={i}>
            <div className="space-y-3">
              <div className="skeleton h-3 w-24" />
              <div className="skeleton h-4 w-3/4" />
              <div className="skeleton h-4 w-full" />
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}

function ReportView({ report, fmt }: { report: AIReport; fmt: (n: number) => string }) {
  return (
    <div className="space-y-6">
      {/* Hero summary */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="relative overflow-hidden rounded-2xl border border-accent/30 bg-surface p-8"
      >
        <div className="absolute -right-16 -top-16 size-64 rounded-full bg-accent/10 blur-3xl" />
        <div className="relative grid grid-cols-1 gap-6 md:grid-cols-[1fr_auto]">
          <div className="space-y-4">
            <div className="inline-flex items-center gap-2 rounded-full border border-accent/30 bg-accent/10 px-2 py-0.5">
              <Sparkles className="size-3 text-accent" />
              <span className="font-mono text-[10px] font-bold uppercase tracking-widest text-accent">
                Wealth Intelligence
              </span>
            </div>
            <h2 className="font-display text-2xl font-medium leading-tight text-balance">
              {report.summary}
            </h2>
            <div className="flex flex-wrap gap-6 pt-2">
              <ScoreStat label="Health" value={report.healthScore} />
              <ScoreStat label="Discipline" value={report.disciplineScore} />
              <ScoreStat label="Savings quality" value={report.savingsQuality} />
              <div>
                <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                  Risk level
                </p>
                <p
                  className={cn(
                    "mt-1 font-display text-xl capitalize",
                    report.riskLevel === "low" && "text-emerald-400",
                    report.riskLevel === "moderate" && "text-amber-400",
                    report.riskLevel === "elevated" && "text-orange-400",
                    report.riskLevel === "high" && "text-rose-400",
                  )}
                >
                  {report.riskLevel}
                </p>
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <Card title="AI Insights" description="What's happening in your finances">
          <ul className="space-y-3">
            {report.insights.map((i) => (
              <InsightRow key={i.id} insight={i} />
            ))}
          </ul>
        </Card>
        <Card title="Recommendations" description="What to do about it">
          <ul className="space-y-3">
            {report.recommendations.map((i) => (
              <InsightRow key={i.id} insight={i} />
            ))}
          </ul>
        </Card>
      </div>

      <p className="text-right font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
        Generated {new Date(report.generatedAt).toLocaleString()}
      </p>
    </div>
  );
}

function ScoreStat({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
        {label}
      </p>
      <p className="mt-1 font-display text-2xl font-semibold tracking-tight">
        {value.toFixed(0)}
        <span className="ml-0.5 font-mono text-xs text-muted-foreground">/100</span>
      </p>
    </div>
  );
}

function InsightRow({ insight }: { insight: AIInsight }) {
  const Icon =
    insight.kind === "warning"
      ? AlertTriangle
      : insight.kind === "win"
        ? Trophy
        : insight.kind === "forecast"
          ? TrendingUp
          : Compass;
  const color =
    insight.kind === "warning"
      ? "text-amber-400 bg-amber-400/10 border-amber-400/20"
      : insight.kind === "win"
        ? "text-emerald-400 bg-emerald-400/10 border-emerald-400/20"
        : "text-accent bg-accent/10 border-accent/20";

  return (
    <li className="flex gap-3 rounded-lg border border-border bg-surface/40 p-3">
      <div className={cn("grid size-8 shrink-0 place-items-center rounded-md border", color)}>
        <Icon className="size-4" />
      </div>
      <div className="min-w-0">
        <p className="text-sm font-medium">{insight.title}</p>
        <p className="mt-0.5 text-xs text-muted-foreground">{insight.body}</p>
      </div>
    </li>
  );
}

function ChatPanel({ snapshot }: { snapshot: ReturnType<typeof buildSnapshot> }) {
  const transport = useMemo(
    () =>
      new DefaultChatTransport({
        api: "/api/chat",
        prepareSendMessagesRequest({ messages }) {
          return { body: { messages, snapshot } };
        },
      }),
    [snapshot],
  );

  const { messages, sendMessage, status } = useChat({
    transport,
    onError: (e) => toast.error(e.message || "Chat failed"),
  });

  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages]);

  const busy = status === "submitted" || status === "streaming";

  const send = async (text: string) => {
    if (!text.trim() || busy) return;
    setInput("");
    await sendMessage({ text: text.trim() });
  };

  const suggestions = [
    "Where am I overspending this month?",
    "How much did I save in the last 3 months?",
    "Suggest a better budget for me.",
    "What's my biggest financial risk?",
  ];

  return (
    <div className="w-full">
      <Card className="!p-0 overflow-hidden rounded-xl shadow-lg" title={undefined}>
        <div className="border-b border-border bg-surface-2/40 px-5 py-3">
          <div className="flex items-center gap-2.5">
            <div className="grid size-8 place-items-center rounded-full bg-accent/15 text-accent">
              <Sparkles className="size-4" />
            </div>
            <div className="min-w-0">
              <h3 className="text-sm font-semibold">Wealth</h3>
              <p className="text-[11px] text-muted-foreground">Your AI financial analyst</p>
            </div>
            <span className="ml-auto inline-flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-2 py-0.5 font-mono text-[9px] uppercase tracking-widest text-emerald-400">
              <span className="size-1.5 rounded-full bg-emerald-400" /> Online
            </span>
          </div>
        </div>

        <div
          ref={scrollRef}
          className="scrollbar-thin flex min-h-[45vh] flex-col gap-3 overflow-y-auto bg-background/40 px-4 py-4"
        >
          {messages.length === 0 ? (
            <div className="space-y-3 py-2">
              <p className="text-center text-xs text-muted-foreground">
                Start a conversation — tap a suggestion or type a question.
              </p>
              <div className="flex flex-wrap justify-center gap-2">
                {suggestions.map((s) => (
                  <button
                    key={s}
                    onClick={() => send(s)}
                    className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs text-muted-foreground transition hover:border-accent/40 hover:text-foreground"
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <>
              {messages.map((m: UIMessage) => (
                <Message key={m.id} message={m} />
              ))}
              {busy && messages[messages.length - 1]?.role === "user" && (
                <div className="flex justify-start">
                  <div className="flex items-center gap-1.5 rounded-2xl rounded-bl-sm bg-surface-2 px-3.5 py-2.5">
                    <span className="size-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:-0.3s]" />
                    <span className="size-1.5 animate-bounce rounded-full bg-muted-foreground [animation-delay:-0.15s]" />
                    <span className="size-1.5 animate-bounce rounded-full bg-muted-foreground" />
                    <span className="ml-1 text-xs text-muted-foreground">Thinking…</span>
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            send(input);
          }}
          className="border-t border-border bg-surface-2/30 p-2.5"
        >
          <div className="flex items-center gap-2">
            <Input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="iMessage"
              disabled={busy}
              autoFocus
              className="rounded-full border-border/60 bg-surface"
            />
            <Button
              type="submit"
              disabled={busy || !input.trim()}
              size="icon"
              className="size-9 rounded-full"
            >
              <Send className="size-4" />
            </Button>
          </div>
        </form>
      </Card>
    </div>
  );
}

function Message({ message }: { message: UIMessage }) {
  const text = message.parts.map((p) => (p.type === "text" ? p.text : "")).join("");
  if (message.role === "user") {
    return (
      <div className="flex justify-end">
        <div className="max-w-[75%] rounded-2xl rounded-br-sm bg-accent px-3.5 py-2 text-sm text-accent-foreground shadow-sm">
          {text}
        </div>
      </div>
    );
  }
  return (
    <div className="flex justify-start">
      <div className="max-w-[80%] whitespace-pre-wrap rounded-2xl rounded-bl-sm bg-surface-2 px-3.5 py-2 text-sm leading-relaxed text-foreground shadow-sm">
        {text}
      </div>
    </div>
  );
}
